### ISSUE TITLE
Comparison to other Collection libraries

### ISSUE THREAD

**Issue by JanecekPetr** [vsonnier/hppcrt#50]
Hello,

I'm interested to see a comparison to other libraries - both hppc and hppc-rt seem to be fairly active nowadays, why should I pick hppc-rt? Is it really RT as it claims? How does it compare to fastutil, Javolution, [SmoothieMap](https://github.com/OpenHFT/SmoothieMap), Koloboke?

I see you have quite a lot of JMH benchmarks in there, so would be interested to see the results on a wiki page or something.

Or, which would be much, much better - contribute benchmarks for hppc-rt to other libraries so that they have a direct comparison which they can showcase, too.

Thank you,
Petr

**Comment by vsonnier** [comment]
Why HPPC-RT ? Well, the goal has been for me to have Zero garbage at runtime, provided containers are pre-sized to your needs. For a modern JVM perspective, this appears fairly ridiculous indeed, because HPPC itself is mostly garbage free, except for iterators creation (included calls that internally creates iterators). On recent JVM I suppose that such generation of small objects is unsignificant, event more so if you have escape analysis working.

Problem is, not everybody is runing modern JVMs, not even everybody is runing Sun/Oracle or its descendants. Some people even run on things that execute Java programs, but not much more can be said about it. Some are embedded, rt-like VM with RT-Gcs, (think like Zing, but with an order of magnitude shorter pauses even) the tradeof being that garbage must still be reduced to a minimum.

So the soft-RT requirement has been, to not geneating garbage at runtime, period.

For the rest, the containers must be resistant to all kind of inputs and exhibit the same kind of speed anytime. That means to be reliable, not necessarily the fastest of the lot. 

In the same spirit, I've added Heaps, and LinkedLists, or CustomHash classes, fastutil-style, so maybe
you may want to use it.

Or else, if the garbage-free requirement is not so strong for you Fastutil may be a good choice, with an incredible diversity of containers and services.

So the benchmarks tried to test execution speed consistency with different key distributions.
As for the choice,
- Fastutil is the closest in implementations, and big brother of all HPPC descendants,
- Koloboke is the king of speed,
- GS has also excellent performance,  with a different implementation.

Javolution was considered, but had so abysmal performance on keys other than Random and Linear that I've excluded from the bench (I wanted the benchs to complete during the night...)

As for SmoothieMap it has just came along, I'll study it when I have time.

Benchmarks: https://gist.github.com/vsonnier/518e438b5ee2d7c7ec95

**Comment by JanecekPetr** [comment]
Thank you, that actually answers my question. A last one - I see how this compares to other libraries and the comparison is very exhausting. The thing I'm missing is the comparison to the original HPPC. Is this a small fork, or a complete overhaul? Are you going to try to incorporate your changes back to HPPC? If not, do you have any comparison / intend to do one / accept pull requests for such comparisons - both speed-wise and garbage-creation-wise?

**Comment by vsonnier** [comment]
I've never intended to be a "competitor" for the regular HPPC, so I've not been tempted to bench against because our goals are slightly different.    
When I have some time, I'll add Map benchmarks against HPPC's Map and ScatterMap, since you are intrested.  
Even if for the sake of maintainance I indeed follow HPPC code evolutions (see  https://github.com/vsonnier/hppcrt/issues/40, https://github.com/vsonnier/hppcrt/issues/42 for REALLY big refactorings) the RT fork has diverged enough to have a life of its own, living now in its own namespace ````com.carrotsearch.hppcrt````.
So, I've added [Changes](https://github.com/vsonnier/hppcrt/blob/0.7.x-RT/README.txt) but also purposefully do not adopt some of the more recent changes of HPPC (no ScatterMaps, for instance)

As for the backport, the entirely new containers like Heaps or LinkedLists could be contributed back to HPPC without the pooled iterators and such, if I'm asked to.

**Comment by vsonnier** [comment]
Note that by https://github.com/vsonnier/hppcrt/issues/51, I'll remove CustomHash classes, in favor to a simpler alternative already present in HPPC.

**Comment by JanecekPetr** [comment]
You're actually one of the nicest and most communicative library developers out there. Thank you!

**Comment by vsonnier** [comment]
You are welcome !

**Comment by vsonnier** [comment]
Benchmarks:
[HPPCRT_v072_vs_World.log](https://gist.github.com/vsonnier/53b6ba142879f12f6e56)
